#index:
#    path: /
#    controller: App\Controller\DefaultController::index

media_api_post_media:
    path: /media/send
    methods: POST
    controller: App\Controller\MediaApiController::postMedia
